### ISSUE TITLE
Can't run Popeye: `No resource meta found for networking.k8s.io/v1/ingresses`

### ISSUE THREAD

**Issue by douglascamata** [derailed/popeye#188]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
I cannot run Popeye on my cluster. It shows the message `No resource meta found for networking.k8s.io/v1/ingresses`. Looks like this was supposed to be fixed by #170 (released 0.9.3), but the problem is still there.

**To Reproduce**
1. Get a k8s cluster running 1.18
2. Try to run `popeye`
3. See error

**Expected behavior**
It should work.

**Versions (please complete the following information):**
 - OS: macOS 11.4
 - Popeye: `0.9.5 (commit 35bf31a8629bf5bab6e4f459549beeca423861bf)`
 - K8s: `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.17-gke.1901", GitCommit:"b5bc948aea9982cd8b1e89df8d50e30ffabdd368`

**Comment by douglascamata** [comment]
Probably will be fixed with #182

**Comment by derailed** [comment]
@douglascamata Thank you Douglas for reporting this! It looks like the cluster version is reported differently based on how the cluster was provisioned ie 18 vs 18+ ( this is where I went wrong ;( ). I do like the PR but think we need a more generic solution. I'll take a crack at it in the next drop and see if we're happier...

**Comment by douglascamata** [comment]
No problem, @derailed! I’m glad a quick fix landed. 

Thanks a lot for the fix all for all the open source tools you develop. I use k9s all the time and it’s amazing ❤️

**Comment by derailed** [comment]
Very kind! Thank you Douglas!!

**Comment by texpert** [comment]
Still the same error with popeye 0.9.6 on kubernetes cluster 1.13.12
